'use client'

import { useState } from 'react'
import { supabase, Company } from '@/lib/supabase'
import { useRouter } from 'next/navigation'
import { convertGoogleDriveLink } from '@/lib/googleDrive'
import styles from './page.module.css'

export default function UploadPage() {
  const router = useRouter()
  const [file, setFile] = useState<File | null>(null)
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState<{ type: 'success' | 'error', text: string } | null>(null)
  const [importedCount, setImportedCount] = useState(0)
  const [skippedRows, setSkippedRows] = useState<number[]>([])

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0])
      setMessage(null)
    }
  }

  const parseCSVLine = (line: string): string[] => {
    const result: string[] = []
    let current = ''
    let inQuotes = false
    
    for (let i = 0; i < line.length; i++) {
      const char = line[i]
      
      if (char === '"') {
        inQuotes = !inQuotes
      } else if (char === ',' && !inQuotes) {
        result.push(current.trim())
        current = ''
      } else {
        current += char
      }
    }
    result.push(current.trim())
    return result
  }

  const parseCSV = (csvText: string): { companies: Company[], skipped: number[] } => {
    const lines = csvText.split('\n').map(line => line.trim()).filter(line => line)
    if (lines.length < 2) {
      throw new Error('CSV file must have at least a header row and one data row')
    }

    const headers = parseCSVLine(lines[0]).map(h => h.toLowerCase().replace(/^"|"$/g, ''))
    
    // Expected columns
    const requiredColumns = [
      'company_name',
      'origin_country',
      'sector',
      'base_price',
      'revenue_2022',
      'revenue_2023',
      'growth_rate'
    ]

    // Check if all required columns exist
    const missingColumns = requiredColumns.filter(col => !headers.includes(col))
    if (missingColumns.length > 0) {
      throw new Error(`Missing required columns: ${missingColumns.join(', ')}`)
    }

    const companies: Company[] = []
    const skipped: number[] = []

    for (let i = 1; i < lines.length; i++) {
      const values = parseCSVLine(lines[i]).map(v => v.replace(/^"|"$/g, '').trim())
      
      if (values.length !== headers.length) {
        skipped.push(i + 1)
        continue // Skip malformed rows
      }

      const row: any = {}
      headers.forEach((header, index) => {
        row[header] = values[index] !== undefined ? values[index] : ''
      })
      
      // Ensure logo_url exists in row (even if column doesn't exist in CSV)
      if (!row.hasOwnProperty('logo_url')) {
        row.logo_url = ''
      }

      // Check for empty required fields
      if (!row.company_name || !row.origin_country || !row.sector || !row.growth_rate) {
        skipped.push(i + 1)
        continue
      }

      // Validate and convert growth_rate
      const growthRate = row.growth_rate.trim().toUpperCase()
      if (!['LOW', 'MEDIUM', 'HIGH'].includes(growthRate)) {
        skipped.push(i + 1)
        continue
      }

      // Validate and convert numeric fields
      const basePrice = parseInt(row.base_price, 10)
      const revenue2022 = parseFloat(row.revenue_2022)
      const revenue2023 = parseFloat(row.revenue_2023)

      if (isNaN(basePrice) || isNaN(revenue2022) || isNaN(revenue2023)) {
        skipped.push(i + 1)
        continue
      }

      // All validations passed, create company object
      // Convert Google Drive links to direct image URLs
      const logoUrl = row.logo_url && row.logo_url.trim() 
        ? convertGoogleDriveLink(row.logo_url.trim()) 
        : null

      const company: Company = {
        id: '', // Will be generated by database
        company_name: row.company_name.trim(),
        origin_country: row.origin_country.trim(),
        sector: row.sector.trim(),
        base_price: basePrice,
        revenue_2022: revenue2022,
        revenue_2023: revenue2023,
        growth_rate: growthRate as 'LOW' | 'MEDIUM' | 'HIGH',
        logo_url: logoUrl
      }

      companies.push(company)
    }

    return { companies, skipped }
  }

  const handleUpload = async () => {
    if (!file) {
      setMessage({ type: 'error', text: 'Please select a CSV file' })
      return
    }

    if (!supabase) {
      setMessage({ type: 'error', text: 'Supabase is not configured. Please set environment variables.' })
      return
    }

    setLoading(true)
    setMessage(null)
    setImportedCount(0)
    setSkippedRows([])

    try {
      const text = await file.text()
      const { companies, skipped } = parseCSV(text)

      if (companies.length === 0) {
        setMessage({ 
          type: 'error', 
          text: skipped.length > 0 
            ? `No valid companies found. ${skipped.length} row(s) were skipped due to invalid data.` 
            : 'No valid companies found in CSV file' 
        })
        setSkippedRows(skipped)
        setLoading(false)
        return
      }

      // Prepare data for insert (remove id field as it's auto-generated)
      const insertData = companies.map(({ id, ...company }) => company)

      // Insert companies in batches
      const batchSize = 100
      let inserted = 0

      for (let i = 0; i < insertData.length; i += batchSize) {
        const batch = insertData.slice(i, i + batchSize)
        const { error } = await supabase
          .from('companies')
          .insert(batch)

        if (error) {
          throw new Error(`Error inserting data: ${error.message}`)
        }

        inserted += batch.length
        setImportedCount(inserted)
      }

      let successMessage = `Successfully imported ${inserted} companies!`
      if (skipped.length > 0) {
        successMessage += ` (${skipped.length} row(s) skipped: ${skipped.slice(0, 10).join(', ')}${skipped.length > 10 ? '...' : ''})`
      }
      
      setMessage({ 
        type: 'success', 
        text: successMessage
      })
      setSkippedRows(skipped)
      setFile(null)
      
      // Reset file input
      const fileInput = document.getElementById('csv-file') as HTMLInputElement
      if (fileInput) fileInput.value = ''

    } catch (error: any) {
      setMessage({ 
        type: 'error', 
        text: error.message || 'Failed to import CSV file' 
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <main className={styles.main}>
      <div className={styles.container}>
        <h1 className={styles.title}>Upload Company Data (CSV)</h1>
        
        <div className={styles.uploadSection}>
          <div className={styles.fileInputWrapper}>
            <input
              id="csv-file"
              type="file"
              accept=".csv"
              onChange={handleFileChange}
              className={styles.fileInput}
              disabled={loading}
            />
            <label htmlFor="csv-file" className={styles.fileLabel}>
              {file ? file.name : 'Choose CSV File'}
            </label>
          </div>

          <button
            onClick={handleUpload}
            className={styles.uploadButton}
            disabled={loading || !file}
          >
            {loading ? `Importing... (${importedCount} imported)` : 'Import CSV'}
          </button>
        </div>

        {message && (
          <div className={message.type === 'success' ? styles.success : styles.error}>
            {message.text}
          </div>
        )}

        {skippedRows.length > 0 && (
          <div className={styles.warning}>
            <strong>Skipped Rows:</strong> The following rows were skipped due to invalid or missing data: {skippedRows.slice(0, 20).join(', ')}
            {skippedRows.length > 20 && ` (and ${skippedRows.length - 20} more)`}
            <br />
            <small>Common issues: Empty growth_rate, invalid numbers, or missing required fields</small>
          </div>
        )}

        <div className={styles.infoSection}>
          <h2 className={styles.infoTitle}>CSV Format Requirements</h2>
          <p className={styles.infoText}>
            Your CSV file must have the following columns (in this order):
          </p>
          <ul className={styles.columnsList}>
            <li><strong>company_name</strong> - Name of the company</li>
            <li><strong>origin_country</strong> - Country of origin</li>
            <li><strong>sector</strong> - Business sector</li>
            <li><strong>base_price</strong> - Base price (integer)</li>
            <li><strong>revenue_2022</strong> - Revenue for 2022 (decimal)</li>
            <li><strong>revenue_2023</strong> - Revenue for 2023 (decimal)</li>
            <li><strong>growth_rate</strong> - Growth rate (LOW, MEDIUM, or HIGH)</li>
            <li><strong>logo_url</strong> - URL to company logo image (optional - leave empty for "NO LOGO")</li>
          </ul>
          <a href="/sample-companies.csv" download="sample-companies.csv" className={styles.downloadLink}>
            Download Sample CSV Template
          </a>
        </div>

        <button
          onClick={() => router.push('/')}
          className={styles.backButton}
        >
          Back to Search
        </button>
      </div>
    </main>
  )
}
